<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class NationalitesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $nationalities = [
            ['code' => 'AFG', 'nom' => 'Afghanistan'],
            ['code' => 'ZAF', 'nom' => 'Afrique du Sud'],
            ['code' => 'ALB', 'nom' => 'Albanie'],
            ['code' => 'DZA', 'nom' => 'Algérie'],
            ['code' => 'DEU', 'nom' => 'Allemagne'],
            ['code' => 'AND', 'nom' => 'Andorre'],
            ['code' => 'AGO', 'nom' => 'Angola'],
            ['code' => 'ATG', 'nom' => 'Antigua-et-Barbuda'],
            ['code' => 'SAU', 'nom' => 'Arabie Saoudite'],
            ['code' => 'ARG', 'nom' => 'Argentine'],
            ['code' => 'ARM', 'nom' => 'Arménie'],
            ['code' => 'AUS', 'nom' => 'Australie'],
            ['code' => 'AUT', 'nom' => 'Autriche'],
            ['code' => 'AZE', 'nom' => 'Azerbaïdjan'],
            ['code' => 'BHS', 'nom' => 'Bahamas'],
            ['code' => 'BHR', 'nom' => 'Bahreïn'],
            ['code' => 'BGD', 'nom' => 'Bangladesh'],
            ['code' => 'BRB', 'nom' => 'Barbade'],
            ['code' => 'BEL', 'nom' => 'Belgique'],
            ['code' => 'BLZ', 'nom' => 'Belize'],
            ['code' => 'BEN', 'nom' => 'Bénin'],
            ['code' => 'BTN', 'nom' => 'Bhoutan'],
            ['code' => 'BLR', 'nom' => 'Biélorussie'],
            ['code' => 'MMR', 'nom' => 'Birmanie (Myanmar)'],
            ['code' => 'BOL', 'nom' => 'Bolivie'],
            ['code' => 'BIH', 'nom' => 'Bosnie-Herzégovine'],
            ['code' => 'BWA', 'nom' => 'Botswana'],
            ['code' => 'BRA', 'nom' => 'Brésil'],
            ['code' => 'BRN', 'nom' => 'Brunei'],
            ['code' => 'BGR', 'nom' => 'Bulgarie'],
            ['code' => 'BFA', 'nom' => 'Burkina Faso'],
            ['code' => 'BDI', 'nom' => 'Burundi'],
            ['code' => 'KHM', 'nom' => 'Cambodge'],
            ['code' => 'CMR', 'nom' => 'Cameroun'],
            ['code' => 'CAN', 'nom' => 'Canada'],
            ['code' => 'CPV', 'nom' => 'Cap-Vert'],
            ['code' => 'CAF', 'nom' => 'République centrafricaine'],
            ['code' => 'CHL', 'nom' => 'Chili'],
            ['code' => 'CHN', 'nom' => 'Chine'],
            ['code' => 'CYP', 'nom' => 'Chypre'],
            ['code' => 'COL', 'nom' => 'Colombie'],
            ['code' => 'COM', 'nom' => 'Comores'],
            ['code' => 'COG', 'nom' => 'République du Congo'],
            ['code' => 'COD', 'nom' => 'République démocratique du Congo'],
            ['code' => 'PRK', 'nom' => 'Corée du Nord'],
            ['code' => 'KOR', 'nom' => 'Corée du Sud'],
            ['code' => 'CRI', 'nom' => 'Costa Rica'],
            ['code' => 'CIV', 'nom' => 'Côte d\'Ivoire'],
            ['code' => 'HRV', 'nom' => 'Croatie'],
            ['code' => 'CUB', 'nom' => 'Cuba'],
            ['code' => 'DNK', 'nom' => 'Danemark'],
            // ['code' => 'DJI', 'nom' => 'Djibouti'],
            ['code' => 'DOM', 'nom' => 'République dominicaine'],
            ['code' => 'DMA', 'nom' => 'Dominique'],
            ['code' => 'EGY', 'nom' => 'Égypte'],
            ['code' => 'ARE', 'nom' => 'Émirats arabes unis'],
            ['code' => 'ECU', 'nom' => 'Équateur'],
            ['code' => 'ERI', 'nom' => 'Érythrée'],
            ['code' => 'ESP', 'nom' => 'Espagne'],
            ['code' => 'EST', 'nom' => 'Estonie'],
            ['code' => 'SWZ', 'nom' => 'Eswatini'],
            ['code' => 'USA', 'nom' => 'États-Unis'],
            ['code' => 'ETH', 'nom' => 'Éthiopie'],
            ['code' => 'FJI', 'nom' => 'Fidji'],
            ['code' => 'FIN', 'nom' => 'Finlande'],
            ['code' => 'FRA', 'nom' => 'France'],
            ['code' => 'GAB', 'nom' => 'Gabon'],
            ['code' => 'GMB', 'nom' => 'Gambie'],
            ['code' => 'GEO', 'nom' => 'Géorgie'],
            ['code' => 'GHA', 'nom' => 'Ghana'],
            ['code' => 'GRC', 'nom' => 'Grèce'],
            ['code' => 'GRD', 'nom' => 'Grenade'],
            ['code' => 'GTM', 'nom' => 'Guatemala'],
            ['code' => 'GIN', 'nom' => 'Guinée'],
            ['code' => 'GNB', 'nom' => 'Guinée-Bissau'],
            ['code' => 'GNQ', 'nom' => 'Guinée équatoriale'],
            ['code' => 'GUY', 'nom' => 'Guyana'],
            ['code' => 'HTI', 'nom' => 'Haïti'],
            ['code' => 'HND', 'nom' => 'Honduras'],
            ['code' => 'HUN', 'nom' => 'Hongrie'],
            ['code' => 'IND', 'nom' => 'Inde'],
            ['code' => 'IDN', 'nom' => 'Indonésie'],
            ['code' => 'IRQ', 'nom' => 'Irak'],
            ['code' => 'IRN', 'nom' => 'Iran'],
            ['code' => 'IRL', 'nom' => 'Irlande'],
            ['code' => 'ISL', 'nom' => 'Islande'],
            ['code' => 'ISR', 'nom' => 'Israël'],
            ['code' => 'ITA', 'nom' => 'Italie'],
            ['code' => 'JAM', 'nom' => 'Jamaïque'],
            ['code' => 'JPN', 'nom' => 'Japon'],
            ['code' => 'JOR', 'nom' => 'Jordanie'],
            ['code' => 'KAZ', 'nom' => 'Kazakhstan'],
            ['code' => 'KEN', 'nom' => 'Kenya'],
            ['code' => 'KGZ', 'nom' => 'Kirghizistan'],
            ['code' => 'KIR', 'nom' => 'Kiribati'],
            ['code' => 'KWT', 'nom' => 'Koweït'],
            ['code' => 'LAO', 'nom' => 'Laos'],
            ['code' => 'LSO', 'nom' => 'Lesotho'],
            ['code' => 'LVA', 'nom' => 'Lettonie'],
            ['code' => 'LBN', 'nom' => 'Liban'],
            ['code' => 'LBR', 'nom' => 'Liberia'],
            ['code' => 'LBY', 'nom' => 'Libye'],
            ['code' => 'LIE', 'nom' => 'Liechtenstein'],
            ['code' => 'LTU', 'nom' => 'Lituanie'],
            ['code' => 'LUX', 'nom' => 'Luxembourg'],
            ['code' => 'MKD', 'nom' => 'Macédoine du Nord'],
            ['code' => 'MDG', 'nom' => 'Madagascar'],
            ['code' => 'MYS', 'nom' => 'Malaisie'],
            ['code' => 'MWI', 'nom' => 'Malawi'],
            ['code' => 'MDV', 'nom' => 'Maldives'],
            ['code' => 'MLI', 'nom' => 'Mali'],
            ['code' => 'MLT', 'nom' => 'Malte'],
            ['code' => 'MAR', 'nom' => 'Maroc'],
            ['code' => 'MHL', 'nom' => 'Îles Marshall'],
            ['code' => 'MUS', 'nom' => 'Maurice'],
            ['code' => 'MRT', 'nom' => 'Mauritanie'],
            ['code' => 'MEX', 'nom' => 'Mexique'],
            ['code' => 'FSM', 'nom' => 'Micronésie'],
            ['code' => 'MDA', 'nom' => 'Moldavie'],
            ['code' => 'MCO', 'nom' => 'Monaco'],
            ['code' => 'MNG', 'nom' => 'Mongolie'],
            ['code' => 'MNE', 'nom' => 'Monténégro'],
            ['code' => 'MOZ', 'nom' => 'Mozambique'],
            ['code' => 'NAM', 'nom' => 'Namibie'],
            ['code' => 'NRU', 'nom' => 'Nauru'],
            ['code' => 'NPL', 'nom' => 'Népal'],
            ['code' => 'NIC', 'nom' => 'Nicaragua'],
            ['code' => 'NER', 'nom' => 'Niger'],
            ['code' => 'NGA', 'nom' => 'Nigeria'],
            ['code' => 'NOR', 'nom' => 'Norvège'],
            ['code' => 'NZL', 'nom' => 'Nouvelle-Zélande'],
            ['code' => 'OMN', 'nom' => 'Oman'],
            ['code' => 'UGA', 'nom' => 'Ouganda'],
            ['code' => 'UZB', 'nom' => 'Ouzbékistan'],
            ['code' => 'PAK', 'nom' => 'Pakistan'],
            ['code' => 'PLW', 'nom' => 'Palaos'],
            ['code' => 'PSE', 'nom' => 'Palestine'],
            ['code' => 'PAN', 'nom' => 'Panama'],
            ['code' => 'PNG', 'nom' => 'Papouasie-Nouvelle-Guinée'],
            ['code' => 'PRY', 'nom' => 'Paraguay'],
            ['code' => 'NLD', 'nom' => 'Pays-Bas'],
            ['code' => 'PER', 'nom' => 'Pérou'],
            ['code' => 'PHL', 'nom' => 'Philippines'],
            ['code' => 'POL', 'nom' => 'Pologne'],
            ['code' => 'PRT', 'nom' => 'Portugal'],
            ['code' => 'QAT', 'nom' => 'Qatar'],
            ['code' => 'ROU', 'nom' => 'Roumanie'],
            ['code' => 'GBR', 'nom' => 'Royaume-Uni'],
            ['code' => 'RUS', 'nom' => 'Russie'],
            ['code' => 'RWA', 'nom' => 'Rwanda'],
            ['code' => 'KNA', 'nom' => 'Saint-Christophe-et-Niévès'],
            ['code' => 'SMR', 'nom' => 'Saint-Marin'],
            ['code' => 'VCT', 'nom' => 'Saint-Vincent-et-les-Grenadines'],
            ['code' => 'LCA', 'nom' => 'Sainte-Lucie'],
            ['code' => 'SLV', 'nom' => 'Salvador'],
            ['code' => 'WSM', 'nom' => 'Samoa'],
            ['code' => 'STP', 'nom' => 'Sao Tomé-et-Principe'],
            ['code' => 'SEN', 'nom' => 'Sénégal'],
            ['code' => 'SRB', 'nom' => 'Serbie'],
            ['code' => 'SYC', 'nom' => 'Seychelles'],
            ['code' => 'SLE', 'nom' => 'Sierra Leone'],
            ['code' => 'SGP', 'nom' => 'Singapour'],
            ['code' => 'SVK', 'nom' => 'Slovaquie'],
            ['code' => 'SVN', 'nom' => 'Slovénie'],
            ['code' => 'SOM', 'nom' => 'Somalie'],
            ['code' => 'SDN', 'nom' => 'Soudan'],
            ['code' => 'SSD', 'nom' => 'Soudan du Sud'],
            ['code' => 'LKA', 'nom' => 'Sri Lanka'],
            ['code' => 'SWE', 'nom' => 'Suède'],
            ['code' => 'CHE', 'nom' => 'Suisse'],
            ['code' => 'SUR', 'nom' => 'Suriname'],
            ['code' => 'SYR', 'nom' => 'Syrie'],
            ['code' => 'TJK', 'nom' => 'Tadjikistan'],
            ['code' => 'TZA', 'nom' => 'Tanzanie'],
            ['code' => 'TCD', 'nom' => 'Tchad'],
            ['code' => 'CZE', 'nom' => 'République tchèque'],
            ['code' => 'THA', 'nom' => 'Thaïlande'],
            ['code' => 'TLS', 'nom' => 'Timor oriental'],
            ['code' => 'TGO', 'nom' => 'Togo'],
            ['code' => 'TON', 'nom' => 'Tonga'],
            ['code' => 'TTO', 'nom' => 'Trinité-et-Tobago'],
            ['code' => 'TUN', 'nom' => 'Tunisie'],
            ['code' => 'TKM', 'nom' => 'Turkménistan'],
            ['code' => 'TUR', 'nom' => 'Turquie'],
            ['code' => 'TUV', 'nom' => 'Tuvalu'],
            ['code' => 'UKR', 'nom' => 'Ukraine'],
            ['code' => 'URY', 'nom' => 'Uruguay'],
            ['code' => 'VUT', 'nom' => 'Vanuatu'],
            ['code' => 'VAT', 'nom' => 'Vatican'],
            ['code' => 'VEN', 'nom' => 'Venezuela'],
            ['code' => 'VNM', 'nom' => 'Viêt Nam'],
            ['code' => 'YEM', 'nom' => 'Yémen'],
            ['code' => 'ZMB', 'nom' => 'Zambie'],
            ['code' => 'ZWE', 'nom' => 'Zimbabwe'],
        ];

        foreach ($nationalities as $nationality) {
            DB::table('nationalities')->insert([
                'code' => $nationality['code'],
                'nom' => $nationality['nom'],
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}